### PR TITLE
Create ci.yml for testing with GitHub actions

### PR DESCRIPTION
**Pull request by ghost**
Apparently Travis is no longer free for OSS.

From this thread, it sounds like the julia folks are switching to use GitHub Actions for this instead! :)

I've given that a shot here.

Copied from https://github.com/JuliaLang/Example.jl/blob/master/.github/workflows/ci.yml

### CODE REVIEW

**Comment by ghost** [comment]
Hmm, looks like the tests failed because it doesn't like our Manifest.toml file... i'm just going to delete that and add package `compat` bounds instead, since that's the more modern thing to do.

**Comment by ghost** [comment]
Okay, i think this is working. The tests are failing because our tests are just plain broken, but let's just merge this, then merge master into #11, and fix the tests there! :)

**Comment by millerjoey** [comment]
Sounds good

**Review by millerjoey — APPROVED** [review]
Broken bc `WARNING: both Mutts and Base export "ismutable"; uses of it in module MuttsTest must be qualified`
but we'll fix it with the name-change PR.

**Pull request merged**
